name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Tag Docker image 
        run: docker tag Test_Image ${{ secrets.DOCKER_HUB_USERNAME }}/wailhadad1221/project_image:latest
     
      - name: Build Docker image with Docker Compose
        run: docker-compose build

      - name: Push Docker image to Docker Hub
        run: docker-compose push 
