name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:   
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
     
      - name: Build Docker image with Docker Compose
        run: docker-compose build -t testimage
        
      - name: Tag Docker image 
        run: docker tag testimage ${{ secrets.DOCKER_HUB_USERNAME }}/project_image:latest 
        
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/project_image:latest 
